### ISSUE TITLE
🚀+Submit+Library:+

### ISSUE THREAD

**Issue by pusolito** [iammohdzaki/KotLibs#2]
**Please Provide following details for your library**
- https://github.com/nacular/doodle 
- Doodle
- A pure Kotlin UI framework for Web and Desktop.
-"JVM","Web","WASM"
- Graphics

**Comment by iammohdzaki** [comment]
Hi,
Your library is listed successfully. Please check it out at https://iammohdzaki.github.io/KotLibs/
Please acknowledge if you can find your library.
Thanks.
