### ISSUE TITLE
🚀 Submit Library: Kotbase

### ISSUE THREAD

**Issue by jeffdgr8** [iammohdzaki/KotLibs#3]
**Please Provide following details for your library**
- Github Project Link: https://github.com/jeffdgr8/kotbase
- Name to be shown: Kotbase
- Description of your project: Kotlin Multiplatform library for Couchbase Lite—a lightweight, embedded, NoSQL JSON document database—supporting SQL++, key/value, and full-text search queries; observability; binary attachments; and data sync.
- Tags: Android, iOS, JVM, Mac, Linux, Windows
- Select One Category: Storage (also should be added to template)

**Comment by iammohdzaki** [comment]
Hi, 
Your library is listed successfully. Please check it out at https://iammohdzaki.github.io/KotLibs/
Please acknowledge if you can find your library.
Thanks.

**Comment by jeffdgr8** [comment]
@iammohdzaki confirmed I can see it.
