### ISSUE TITLE
🚀 Submit Library: 

### ISSUE THREAD

**Issue by theolm** [iammohdzaki/KotLibs#4]
**Please Provide following details for your library**
- Github Project Link 
https://github.com/theolm/rinku
- Name to be shown
Rinku: Deep Link Handling
- Description of your project
Rinku is a lightweight Kotlin Multiplatform library designed to simplify deep link handling across iOS and Android platforms. By abstracting platform-specific details, Rinku enables developers to manage deep links in a unified manner, enhancing code reuse and maintaining consistency across platforms.
- Tags :  "android", "ios"

- Select One Category from Below:
"Architecture"

**Comment by iammohdzaki** [comment]
Hi,
Your library has been successfully added. Please check it at https://iammohdzaki.github.io/KotLibs/
Thanks
![image](https://github.com/iammohdzaki/KotLibs/assets/30112063/09a2afe0-fd4e-414c-86cb-46c8dd959dcf)
