### ISSUE TITLE
🚀 Submit Library: KoVibes

### ISSUE THREAD

**Issue by rubenquadros** [iammohdzaki/KotLibs#5]
**Please Provide following details for your library**
- Github Project Link: https://github.com/rubenquadros/KoVibes 
- Name to be shown: KoVibes
- Description of your project: KoVibes is lightweight, simple to use Kotlin multiplatform library which is a Kotlin wrapper for the Spotify Web API. You don't have to worry about the complexity of authentication or maintaining the auth token. With KoVibes you can simply focus on building your next music app!
- Tags:   "android", "jvm".
- Select One Category from Below:
- "Music"
- "Audio"

**Comment by iammohdzaki** [comment]
Hi, 
Your library has been successfully added. Checkout on https://iammohdzaki.github.io/KotLibs/. 
Thanks
![image](https://github.com/iammohdzaki/KotLibs/assets/30112063/c6e98707-cc5e-4752-acb9-7362cb69a998)
